name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 5' # Every Friday at 06:00 UTC
  push:
    branches:
      - '**'
    tags:
      - 'v*'
    paths-ignore:
      - '**/*.md'
      - '**/*.jpg'
      - '**/*.fzz'
      - '**/*.fzpz'
      - '**/*.xlsx'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write # Create/update GitHub Releases
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Secrets file
      run: mv include/Secrets.template.h include/Secrets.h

    - name: Dependency cache
      uses: actions/cache@v5
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.9'

    - name: Setup PlatformIO
      run: pip install --upgrade platformio

    - name: Build Project
      run: pio run

    - name: Get Version info
      if: startsWith(github.event.ref, 'refs/tags/v')
      id: tagver
      uses: ChrSchu90/GitTagSemanticVersion@v1.1

    - name: Create Release
      if: ${{ steps.tagver.outputs.is_valid == 'true' }}
      uses: softprops/action-gh-release@v2
      with:
        fail_on_unmatched_files: true
        tag_name: ${{ steps.tagver.outputs.version_tag }}
        prerelease: ${{ steps.tagver.outputs.is_prerelease == 'true' }}  
        files: |
          ./.pio/build/nodemcu-32s/firmware.bin
